runtime: python39  # Specifies the Python runtime version
entrypoint: gunicorn -b :$PORT app:app  # Gunicorn as the WSGI server

instance_class: F4  # Use a larger instance type for better performance
# instance_class and automatic scaling options (optional)
automatic_scaling:
  max_instances: 10  # Set this to a number below 32, based on your needs
  min_instances: 1    # Keep a minimum number to ensure availability
  target_cpu_utilization: 0.6  # Adjust CPU utilization to manage scaling
  target_throughput_utilization: 0.6


handlers:
  # Serve static files in the /static directory
  - url: /static
    static_dir: static

  # Optionally, add a handler for favicon.ico
  - url: /favicon.ico
    static_files: static/images/logo.png
    upload: static/images/logo.png
