runtime: python39  # Specifies the Python runtime version
entrypoint: gunicorn -b :$PORT app:app  # Gunicorn as the WSGI server

# instance_class and automatic scaling options (optional)
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

